### ISSUE TITLE
Error when a species not matched with `tnrs_match_names()`

### ISSUE THREAD

**Issue by daijiang** [ropensci/rotl#128]
Try `rotl::tnrs_match_names("Abies sp")`, which gives

```
Error in res[["results"]][[res_id]][["matches"]][[match_id]] : 
  subscript out of bounds
In addition: Warning message:
Abies sp are not matched 
```

I also add a comment [here](https://github.com/ropensci/rotl/commit/98cecc4a1580e9557acb67339eb560c63a6c2129#r39488505).

Thanks!

**Comment by fmichonneau** [comment]
thanks for the report @daijiang. 
This part of the code is quite brittle and OTL changed the format of the results returned by the API recently and I think the error is arising.
I tried to investigate quickly but couldn't get the root cause. I saw your comment but I think it's a little more involved than that. If you have time to try to find a fix, please go ahead. If not I'll try to investigate more later.
