### ISSUE TITLE
New CRAN release

### ISSUE THREAD

**Issue by dwinter** [ropensci/rotl#63]
I guess the CRAN release is now throwing errors for a lot of users. 

Should we start working towards a new CRAN release. If so we could start a milestone, which would give us a good way to track which outstanding issues need to be closed beforehand?

**Comment by fmichonneau** [comment]
We are basically ready to go for a CRAN release.

I have hit a bug with readxl that doesn't want to read the egg.xls from the meta-analysis vignette on Windows. I'm currently building the package on win-builder using the gdata package instead of readxl (it seems to work fine at least on my laptop).

I have gotten an email from the CRAN maintainers a couple of weeks ago, so I'd rather submit it sooner rather than later.

I think all issues are mostly enhancements that we can address once we receive the reviews on the manuscript. Does that sound good?

**Comment by dwinter** [comment]
Sounds good to me, just wanted to make sure users weren't being turned away
by hitting these errors

**Comment by fmichonneau** [comment]
Yes, I agree. I got the results back from win-builder and it seems to be good for now. I'll prepare for release.

**Comment by fmichonneau** [comment]
Just sent to CRAN.

**Comment by dwinter** [comment]
Nice work!

On Mon, Feb 1, 2016 at 2:37 PM, Francois Michonneau <
notifications@github.com> wrote:

> Just sent to CRAN.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/rotl/issues/63#issuecomment-178205769>.
>



-- 
David Winter
Postdoctoral Research Associate
Center for Evolutionary Medicine and Informatics
The Biodesign Institute
Arizona State University

ph: +1 480 519 5113
w: www.david-winter.info
lab: http://cartwrig.ht/lab/
blog: sciblogs.co.nz/the-atavism

**Comment by fmichonneau** [comment]
On CRAN now

**Comment by sckott** [comment]
thanks for doing using the detailed notes in releases https://github.com/ropensci/rotl/releases/tag/v0.5.0
